#!/bin/sh
TEXMFHOME=`kpsewhich -var-value TEXMFHOME`/tex/latex/
TARGET=`pwd`/latex/flexplot.sty
echo "Creating a symlink to $TARGET in $TEXMFHOME"
ln -i -s $TARGET -t $TEXMFHOME
echo "Running mktexlsr"
mktexlsr
